services:

    #
    # Object Managers
    #
    beloop.object_manager.squarespace_page:
        parent: beloop.abstract_manager
        arguments:
            - %beloop.entity.squarespace_page.class%
