language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: $SYMFONY_VERSION="^3.0.0"
    - php: 7.3
      env: $SYMFONY_VERSION="^3.0.0"
  allow_failures:
    - php: nightly
      env: $SYMFONY_VERSION="^3.0.0"

before_install:
  - composer self-update
  - composer config preferred-install source
  - 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi;'

install: composer install --no-interaction --no-progress

script:
  - vendor/bin/phpunit -v
