services:

    #
    # Directors
    #
    beloop.director.user:
        class: Beloop\Component\Core\Services\ObjectDirector
        lazy: true
        arguments:
            - '@beloop.object_manager.user'
            - '@beloop.repository.user'
            - '@beloop.factory.user'
