services:

    #
    # Services
    #

    #
    # Manager
    #
    beloop.manager.user:
        class: Beloop\Component\User\Services\UserManager
        arguments:
            - '@beloop.object_manager.user'
            - '@beloop.repository.user'

    #
    # CSV file transformer
    #
    beloop.csv_transformer.user:
        class: Beloop\Component\User\Transformer\ExtractUsersFromCSV
        arguments:
            - '@beloop.factory.user'
            - ['Email', 'First Name', 'Last Name']
        calls:
           - [setDelimiter, [';']]

    #
    # User enrollment
    #
    beloop.user_enrollment:
        class: Beloop\Component\Course\Services\UserEnrollment
        arguments:
            - '@beloop.csv_transformer.user'
            - '@beloop.manager.user'
            - '@beloop.director.user'
