services:

    #
    # Directors
    #
    beloop.director.squarespace_page:
        class: Beloop\Component\Core\Services\ObjectDirector
        lazy: true
        arguments:
            - '@beloop.object_manager.squarespace_page'
            - '@beloop.repository.squarespace_page'
            - '@beloop.factory.squarespace_page'
